### PR TITLE
tracy memory allocation profiling

### PR DESCRIPTION
**Pull request by CatCode79**
After a bit of fussing and trying, the solution was very simple, a classic!

There is nothing to add to the setup, simply tracy now displays the estimated memory allocation.

### CODE REVIEW

**Comment by Davidster** [comment]
awesome! looking forward to trying this out. never used the global allocator thing before :eyes:

**Comment by Davidster** [comment]
I tried running it with tracy enabled but it was very slow, it was taking a lot longer for the application to start. Around 90 seconds with the tracy features enabled and 17s without it. I wanted to try to comment out the [`emit_alloc` and `emit_free` calls](https://docs.rs/tracy-client/latest/src/tracy_client/lib.rs.html#206) to see if those are the offenders but I couldn't figure out how to modify the tracy-client code and have it be used in ikari. Do you know how to do it?

**Comment by CatCode79** [comment]
I noticed it but I was hoping it was my slow notebook, I try to add two compilation features for each tracy debugging feature, in fact I think we will use allocation debugging relatively little.

**Comment by CatCode79** [comment]
I renamed the profile-with-tracy feature tracy, simpler and shorter.
I added the tracy-n-alloc feature, it is not additive but cumulative (ie it also contains the tracy feature).
Let me know if you like it this way, I'm in doubt whether to make it additive instead (that is, two features should be added to the command line instead of just one).

**Review by Davidster — APPROVED** [review]
nice, I like tracy over profile-with-tracy!

**Pull request merged**
